
services:
  postgresql:
    restart: always
    image: postgres:13-trixie
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: quiz
    ports:
      - "5332:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080